### ISSUE TITLE
No autoload property for composer.json

### ISSUE THREAD

**Issue by uginroot** [fluffy-critter/php-urljoin#3]
Please add autoload for composer.json

**Comment by fluffy-critter** [comment]
Will do. For my own future reference, https://getcomposer.org/doc/04-schema.md#autoload

**Comment by fluffy-critter** [comment]
Done in 23e9c60

**Comment by uginroot** [comment]
Promptly. But psr-4 does not work for individual functions. You need to connect a specific file. There is an example [here](https://stackoverflow.com/questions/24171078/composer-psr-how-to-autoload-functions)

**Comment by fluffy-critter** [comment]
Ah, sorry about that! I don’t work in PHP much. Do you mind doing this and opening a PR so that I can be sure it’s correct?

**Comment by uginroot** [comment]
I did https://github.com/fluffy-critter/php-urljoin/pull/4

**Comment by fluffy-critter** [comment]
Yes, thanks so much!
